server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 800
    min-spare-threads: 100

spring:
  application:
    name: kafkamanager
  datasource:
    kafka-manager:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/kafka_manager?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: admin
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB

logging:
  config: classpath:logback-spring.xml

custom:
  idc: cn
  jmx:
    max-conn: 10

account:
  ldap:

kcm:
  enabled: false
  n9e:
    base-url: http://127.0.0.1:8080
    user-token: 12345678
    timeout: 300
    account: km
    script-file: kcm_script.sh

monitor:
  enabled: false
  n9e:
    nid: 2
    user-token: 1234567890
    mon:
      base-url: http://127.0.0.1:8032
    sink:
      base-url: http://127.0.0.1:8008

notify:
  kafka:
    cluster-id: 95
    topic-name: didi-kafka-notify
  order:
    detail-url: http://127.0.0.1
