version: "3"

services:
  
  knowstreaming-manager:
    image: km_manage:1.1
    container_name: knowstreaming-manager
    privileged: true
    restart: always
    depends_on:
      - elasticsearch_single
      - kmysql
    links:
      - elasticsearch_single
      - kmysql
    expose:
      - 80
    environment:
      TZ: Asia/Shanghai

      SERVER_MYSQL_ADDRESS: kmysql:3306
      SERVER_MYSQL_DB: know_streaming
      SERVER_MYSQL_USER: root
      SERVER_MYSQL_PASSWORD: admin2022_

      SERVER_ES_ADDRESS: elasticsearch_single:9200

      JAVA_OPTS: -Xmx1g -Xms1g
    networks:
      - ks
#    日志文件持久化路径
#    volumes:
#      - /Users/haoqi/Downloads/ks/manage/log:/logs
  knowstreaming-ui:
    image: km:1.0
    container_name: knowstreaming-ui
    restart: always
    ports:
      - '80:80'
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - knowstreaming-manager
    links:
      - knowstreaming-manager
    networks:
      - ks


  elasticsearch_single:
    image: docker.io/library/elasticsearch:7.6.2
    container_name: elasticsearch_single
    restart: always
    expose:
      - 9200
      - 9300
#    对外访问
#    ports:
#      - '9200:9200'
#      - '9300:9300'
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
#    数据文件持久化路径
#    记录实时指标信息
#    volumes:
#      - /Users/haoqi/Downloads/ks/es/data:/usr/share/elasticsearch/data
    networks:
      - ks
  esinit:
    image: esinit:1.0
    container_name: esinit
    depends_on:
      - elasticsearch_single
    links:
      - elasticsearch_single
    environment:
      TZ: Asia/Shanghai
      SERVER_ES_ADDRESS: elasticsearch_single:9200
    networks:
      - ks

  kmysql:
    image: ks_mysql:1.0
    container_name: kmysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: admin2022_
      MYSQL_DATABASE: know_streaming
    networks:
      - ks
    expose:
      - 3306
#   数据文件持久化路径
#   记录添加的集群基本信息
#    volumes:
#      - /Users/haoqi/Downloads/ks/mysql/data:/data/mysql

networks:
  ks:
    driver: bridge