version: "3"

services:
  
  knowstreaming-manager:
    image: knowstreaming-manager:0.1.0
    container_name: knowstreaming_manager
    privileged: true
    restart: always
    depends_on:
      - elasticsearch-single
      - knowstreaming-mysql
    links:
      - elasticsearch-single
      - knowstreaming-mysql
    expose:
      - 80
    environment:
      TZ: Asia/Shanghai

      SERVER_MYSQL_ADDRESS: knowstreaming-mysql:3306
      SERVER_MYSQL_DB: know_streaming
      SERVER_MYSQL_USER: root
      SERVER_MYSQL_PASSWORD: admin2022_

      SERVER_ES_ADDRESS: elasticsearch-single:9200

      JAVA_OPTS: -Xmx1g -Xms1g
    networks:
      - ks
#    volumes:
#      - /Users/haoqi/Downloads/ks/manage/log:/logs
  knowstreaming-ui:
    image: knowstreaming-ui:0.1.0
    container_name: knowstreaming_ui
    restart: always
    ports:
      - '80:80'
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - knowstreaming-manager
    links:
      - knowstreaming-manager
    networks:
      - ks


  elasticsearch-single:
    image: docker.io/library/elasticsearch:7.6.2
    container_name: elasticsearch_single
    restart: always
    expose:
      - 9200
      - 9300
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
#    volumes:
#      - /Users/haoqi/Downloads/ks/es/data:/usr/share/elasticsearch/data
    networks:
      - ks
  knowstreaming-init:
    image: knowstreaming-init:0.1.0
    container_name: knowstreaming_init
    depends_on:
      - elasticsearch-single
    links:
      - elasticsearch-single
    environment:
      TZ: Asia/Shanghai
      SERVER_ES_ADDRESS: elasticsearch_single:9200
    networks:
      - ks

  knowstreaming-mysql:
    image: knowstreaming-mysql:0.1.0
    container_name: knowstreaming_mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: admin2022_
      MYSQL_DATABASE: know_streaming
    networks:
      - ks
    expose:
      - 3306
#    volumes:
#      - /Users/haoqi/Downloads/ks/mysql/data:/data/mysql

networks:
  ks:
    driver: bridge