version: "3"

services:
  
  knowstreaming-manager:
    image: knowstreaming/knowstreaming-manager:0.2.0-test
    container_name: knowstreaming-manager
    privileged: true
    restart: always
    depends_on:
      - elasticsearch-single
      - knowstreaming-mysql
    expose:
      - 80
    command:
      - /bin/sh
      - /ks-start.sh
    environment:
      TZ: Asia/Shanghai

      SERVER_MYSQL_ADDRESS: knowstreaming-mysql:3306
      SERVER_MYSQL_DB: know_streaming
      SERVER_MYSQL_USER: root
      SERVER_MYSQL_PASSWORD: admin2022_

      SERVER_ES_ADDRESS: elasticsearch-single:9200

      JAVA_OPTS: -Xmx1g -Xms1g

#    extra_hosts:
#      - "hostname:x.x.x.x"
#    volumes:
#      - /ks/manage/log:/logs
  knowstreaming-ui:
    image: knowstreaming/knowstreaming-ui:0.2.0-test1
    container_name: knowstreaming-ui
    restart: always
    ports:
      - '18092:80'
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - knowstreaming-manager
#    extra_hosts:
#      - "hostname:x.x.x.x"

  elasticsearch-single:
    image: docker.io/library/elasticsearch:7.6.2
    container_name: elasticsearch-single
    restart: always
    expose:
      - 9200
      - 9300
#    ports:
#      - '9200:9200'
#      - '9300:9300'
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
#    volumes:
#      - /ks/es/data:/usr/share/elasticsearch/data

  knowstreaming-init:
    image: knowstreaming/knowstreaming-manager:0.2.0-test
    container_name: knowstreaming_init
    depends_on:
      - elasticsearch-single
    command:
      - /bin/bash
      - /es_template_create.sh
    environment:
      TZ: Asia/Shanghai
      SERVER_ES_ADDRESS: elasticsearch-single:9200


  knowstreaming-mysql:
    image: knowstreaming/knowstreaming-mysql:0.2.0-test
    container_name: knowstreaming-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: admin2022_
      MYSQL_DATABASE: know_streaming
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
#    ports:
#      - '3306:3306'
#    volumes:
#      - /ks/mysql/data:/data/mysql